### ISSUE TITLE
Chart[Postgres]: Postgres containers are crashing

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#318]
```
[2023-09-07 23:03:21] [ERROR] connection to database failed
[2023-09-07 23:03:21] [DETAIL] 
2023-09-07 23:03:21.509 GMT [175] FATAL:  password authentication failed for user "repmgr"
```
<img width="1175" alt="Screenshot 2023-09-08 at 9 03 35 AM" src="https://github.com/hashgraph/full-stack-testing/assets/811437/a93de0ac-62f5-433c-8921-2bcd5af11993">

**Comment by deepak-swirlds** [comment]
They are crashing because probably you recreated the environment and did not delete the PV holding the data
K8s uses 
PV - Persistent Volume - volume holding the data
PVC - Persistent Volume Claim - claim in the deployment / statefulset

NOTE: use with care if you have important information in PV it will be deleted
To delete all PVs use below command :

kubectl delete pv --all &  kubectl delete pvc --all

Then re-create the environment.

Please reopen the ticket if this is does solve it.
